default: &default
  title: Z
  host: l.com:3000
  email_from: noreply@projetc-z.org

development:
  <<: *default
  admin_emails:
    #- iamalazyrat@gmail.com
    #- tangmingming@haodou.com
  admin_group: 管理员
  guest_group: 访客

test:
  <<: *default
  admin_emails:
    - admin@example.com

production:
  <<: *default

  admin_emails:
    # - admin@example.com
    #- iamalazyrat@gmail.com

  admin_group: 管理员
  guest_group: 访客

