default: &default
  title: Z
  host: l.com:3000

development:
  <<: *default
  admin_emails:
    - admin@example.com

test:
  <<: *default
  admin_emails:
    - admin@example.com

production:
  <<: *default

  admin_emails:
    # - admin@example.com
