default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: z_dev

test:
  <<: *default
  database: z_test

production:
  <<: *default
  database: z_prd

