default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: z_development

test:
  <<: *default
  database: z_test

bing:
  adapter: mysql2
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  database: bing

production:
  <<: *default
  #database: z_production
  database: z_development
  #username: z
  #password: <%= ENV['Z_DATABASE_PASSWORD'] %>

